# general settings
# name: basic_nf15nb30_b6_4e-4_REDS_BI_x4
experiments_root: exp_video/train/mem_track/
model_type: BasicVSRModel  # BasicVSRModel BasicVSRGanModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: /media/ahut/disk/datasets/REDS/train/train_sharp
    dataroot_lq: /media/ahut/disk/datasets/REDS/train/train_sharp_bicubic/X4/
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    is_train: true
    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 10
    prefetch_mode: ~
    pin_memory: true

  val:
    name: REDS4
    type: REDSRecurrentDataset
    dataroot_gt: /media/ahut/disk/datasets/REDS/train/train_sharp    #val_sharp
    dataroot_lq: /media/ahut/disk/datasets/REDS/train/train_sharp_bicubic/X4/    #val_sharp_bicubic/X4
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    is_train: false
    num_frame: 20
    gt_size: ~
    interval_list: [1]
    random_reverse: false
    use_flip: false
    use_rot: false

# network structures
network_g:
  type: BasicVSR # BasicVSR BasicVSR_V2 BasicVSR_FNO
  num_feat: 64
  # extract_block: 12
  num_block: 30
  spynet_path: pretrained_models/network-sintel-final.pytorch

# path
path:
  pretrain_network_g: 
  strict_load_g: false
  resume_state:
  
# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000, 50000]
    restart_weights: [1, 0.5, 0.25]
    eta_min: !!float 1e-7

  total_iter: 50000
  warmup_iter: -1  # no warm up
  fix_iter: 5000
  spynet_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

  # use_hidden_closs: True

# validation settings
val:
  val_freq: !!float 5e2
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
